require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/production_stages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductionStage. As you add validations to ProductionStage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductionStage.create! valid_attributes
      get production_stages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      production_stage = ProductionStage.create! valid_attributes
      get production_stage_url(production_stage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_production_stage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      production_stage = ProductionStage.create! valid_attributes
      get edit_production_stage_url(production_stage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductionStage" do
        expect {
          post production_stages_url, params: { production_stage: valid_attributes }
        }.to change(ProductionStage, :count).by(1)
      end

      it "redirects to the created production_stage" do
        post production_stages_url, params: { production_stage: valid_attributes }
        expect(response).to redirect_to(production_stage_url(ProductionStage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductionStage" do
        expect {
          post production_stages_url, params: { production_stage: invalid_attributes }
        }.to change(ProductionStage, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post production_stages_url, params: { production_stage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested production_stage" do
        production_stage = ProductionStage.create! valid_attributes
        patch production_stage_url(production_stage), params: { production_stage: new_attributes }
        production_stage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the production_stage" do
        production_stage = ProductionStage.create! valid_attributes
        patch production_stage_url(production_stage), params: { production_stage: new_attributes }
        production_stage.reload
        expect(response).to redirect_to(production_stage_url(production_stage))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        production_stage = ProductionStage.create! valid_attributes
        patch production_stage_url(production_stage), params: { production_stage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested production_stage" do
      production_stage = ProductionStage.create! valid_attributes
      expect {
        delete production_stage_url(production_stage)
      }.to change(ProductionStage, :count).by(-1)
    end

    it "redirects to the production_stages list" do
      production_stage = ProductionStage.create! valid_attributes
      delete production_stage_url(production_stage)
      expect(response).to redirect_to(production_stages_url)
    end
  end
end
